package com.assentify.sdk.RemoteClient.Models
data class ContextAwareSigningModel(
    val statusCode: Int,
    val data: DataModel
)

data class DataModel(
    val selectedTemplates: List<Int>,
    val header: String?,
    val confirmationMessage: String?,
    val subHeader: String?,
    val svgLogoUrl: String?,
    val autoDownload: Boolean,
    val enableDigitalSignature: Boolean,
    val hideSignatureBoard: Boolean,
    val otpInputType:Int?,
    val enableOtp: Boolean,
    val otpSize: Int?,
    val otpExpiryTime: Double?,
    val otpTargets: List<String> = emptyList(),
    val autoGeneratedSignatureValues: List<String> = emptyList(),
    val enableSignatureVisualVerifier:Boolean?,
    val faceImageSource: String?,
    val isNormalClick: Boolean?,
    val smsProvider: Int?,
    val whatsappProvider: Int?,
    val otpFormat: Int?,
)

