package com.assentify.sdk.Models

enum class AIStatusEnum {
    Error,
    InputFormatError,
    FaceFound,
    NoFaceFound,
    MultipleFacesFound,
    Match,
    NoMatch,
    PassportRead,
    CannotReadPassport,
    CardDetected,
    NoCardDetected,
    TemplateEnrolled,
    PixelizationComplete,
    LivenessSuccessful,
    LivenessFailed,
    CornersDetected,
    DocumentScanned,
    PassportDecoded,
    PassportPartiallyDecoded,
    OCRTextFound,
    NoOCRTextFound,
    TableRead,
    DetectPassportSuccessful,
    DetectPassportFailed,
    DetectIDSuccessful,
    DetectIDFailed,
    UpdateIDSuccessful,
    UpdateIDFailed,
    OCRSuccessful,
    OCRFailed,
    NoFaceFoundWithinBounds,
    NoMRZFound,
    PassportReadingError
}
