package com.assentify.sdk.Flow.FlowController

import com.assentify.sdk.Core.Constants.UiLanguage
import com.assentify.sdk.Flow.BlockLoader.BaseTheme

data class FlowStrings(
    // Common
    val next: String,
    val retry: String,
    val skip: String,
    val letsStart: String,
    val accept: String,
    val decline: String,

    // BlockLoader
    val onboardingTitle: (count: Int) -> String,
    val onboardingSubtitle: String,
    val thankYou: String,
    val completedSteps: (count: Int) -> String,

    // Step meta
    val stepTermsName: String,
    val stepTermsDesc: String,
    val stepIdName: String,
    val stepIdDesc: String,
    val stepFaceName: String,
    val stepFaceDesc: String,
    val stepDataEntryName: String,
    val stepDataEntryDesc: String,
    val stepSigningName: String,
    val stepSigningDesc: String,

    // ID Step
    val restOfWorld: String,
    val chooseCountry: String,
    val selectDocument: String,
    val passport: String,
    val supportedIds: String,
    val viewMore: String,
    val idDisclaimer: (flowName: String) -> String,
    val selectCountryPlaceholder: String,
    val presentPassport: String,
    val presentId: String,
    val watchCapturePassport: String,
    val watchCaptureId: String,
    val lightingTip: String,

    // Face Step
    val faceMatch: String,
    val watchCaptureFace: String,
    val faceCaptureTip: String,
    val verificationSuccess: String,
    val verificationFail: String,
    val verificationSuccessMsg: String,
    val verificationFailMsg: String,
    val confirmProceed: String,
    val provideSupportingId: String,
    val overrideProceed: String,
    val matchLabel: String,
    val processingFace: String,
    val uploadingFace: String,
    val faceErrorLiveTitle: String,
    val faceErrorGeneralTitle: String,
    val faceErrorLiveMsg: String,
    val faceErrorGeneralMsg: String,

    // ID Events
    val processingId: String,
    val uploadingId: String,
    val idProcessedOk: String,
    val idErrorTitle: String,
    val idErrorMsg: String,
    val captureBackId: String,
    val flipCardMsg: String,
    val expectedCardType: String,
    val livenessErrorTitle: String,
    val livenessErrorMsg: (flowName: String) -> String,
    val passportExpiredTitle: String,
    val passportExpiredMsg: String,
    val wrongTemplateTitle: String,
    val wrongTemplateMsg: (flowName: String) -> String,

    // Submit Step
    val readyToSubmit: String,
    val swipeToConfirm: String,
    val submissionError: String,
    val swipeToSubmit: String,

    // Assisted Data Entry
    val somethingWentWrong: String,

    // QR Step
    val captureQr: String,
    val watchCaptureQr: String,
    val qrLightingTip: String,

    // NFC Step
    val nfcCapture: String,
    val nfcInitialFeedback: String,
    val nfcNotSupported: String,
    val nfcReading: String,
    val nfcConnectionLost: String,
    val nfcDetected: String,

    // Context-Aware / Signing
    val iAgreeTerms: String,
    val filesReviewedApproved: String,
    val emailVerificationTitle: String,
    val phoneNumberLabel: String,
    val reviewApproveFiles: String,
    val thankYouForApproving: String,
    val agreementTitle: String,
    val validateOtpFirst: String,
    val acceptTermsAndSign: String,
    val acceptTermsOnly: String,
    val approve: String,

    // Camera feedback – shared
    val holdSteady: String,
    val holdYourHand: String,
    val increaseLighting: String,
    val reduceLighting: String,
    val centerCard: String,

    // Passport camera feedback
    val movePassportCloser: String,
    val movePassportFurther: String,

    // ID card camera feedback
    val moveIdCloser: String,
    val moveIdFurther: String,

    // Face camera feedback
    val moveFaceCloser: String,
    val moveFaceFurther: String,
    val moveFaceLeft: String,
    val moveFaceRight: String,
    val moveFaceUp: String,
    val moveFaceDown: String,
    val winkLeftEye: String,
    val winkRightEye: String,
    val blinkEyes: String,
    val tiltHeadRight: String,
    val tiltHeadLeft: String,
    val turnHeadRight: String,
    val turnHeadLeft: String,
    val lowerHead: String,
    val raiseHead: String,
    val faceWithinCircle: String,
    val centerFace: String,
    val multipleFacesDetected: String,

    // PDF Viewer
    val failedToLoadPdf: String,
    val noPdfViewerFound: String,
    val failedToOpenPdf: String,

    // OTP fields
    val otpLabel: (size: Int) -> String,
    val sendOtp: String,
    val sendingOtp: String,
    val enterOtp: String,
    val verifiedSuccessfully: String,
    val otpVerifying: String,
    val resendOtp: String,
    val resendIn: (countdown: String) -> String,
    val failedToSendOtp: String,
    val invalidOtp: String,
    val invalidEmail: String,
    val invalidPhone: String,
    val fieldRequired: String,
    val minLengthError: (min: Int) -> String,
    val maxLengthError: (max: Int) -> String,
    val invalidValue: String,

    // Stepper
    val stepperProgress: (current: Int, total: Int) -> String,

    // Form fields
    val searchPlaceholder: String,
    val noResultsFound: String,
    val chooseCode: String,

    // Signature pad
    val signatureTitle: String,
    val confirmSignature: String,
    val confirmedSignature: String,

    // Step name format (used in StepCard)
    val stepNameFormat: (n: Int, name: String) -> String,

    // Date picker
    val okButton: String,
    val cancelButton: String,

    // Complete Screen field labels
    val fieldFirstName: String,
    val fieldLastName: String,
    val fieldFatherName: String,
    val fieldMotherName: String,
    val fieldBirthDate: String,
    val fieldExpiryDate: String,
    val fieldCountry: String,
    val fieldNationality: String,
    val fieldDocNumber: String,
    val fieldIdType: String,
    val fieldPlaceOfBirth: String,
    val fieldDocType: String,
    val fieldCivilRegister: String,
    val fieldDateOfIssuance: String,
    val fieldGender: String,
    val fieldMaritalStatus: String,
    val fieldPlaceOfResidence: String,
    val fieldProvince: String,
    val fieldGovernorate: String,
)

private val englishStrings = FlowStrings(
    next = "Next",
    retry = "Retry",
    skip = "Skip",
    letsStart = "Lets Start",
    accept = "Accept",
    decline = "Decline",

    onboardingTitle = { count -> "Complete Your\nOnboarding in $count ${if (count == 1) "Step" else "Steps"}" },
    onboardingSubtitle = "It will include capturing your ID and your face — it's fast, easy, and secure.",
    thankYou = "Thank you!",
    completedSteps = { count -> "Completed $count ${if (count == 1) "Step" else "Steps"} Successfully" },

    stepTermsName = "Terms & Conditions",
    stepTermsDesc = "Read and accept the Terms & Conditions.",
    stepIdName = "Scan Your ID",
    stepIdDesc = "Take a photo of your national ID or passport to verify your identity.",
    stepFaceName = "Take Selfie",
    stepFaceDesc = "Use your camera to securely confirm your identity with a quick selfie scan.",
    stepDataEntryName = "Information Capture",
    stepDataEntryDesc = "Provide basic personal details like name, address, and employment info.",
    stepSigningName = "eKYC Signing",
    stepSigningDesc = "Provide a digital signature to complete onboarding.",

    restOfWorld = "Rest of the world",
    chooseCountry = "Choose your country of residence",
    selectDocument = "Select type of document",
    passport = "Passport",
    supportedIds = "Supported IDs",
    viewMore = "View more",
    idDisclaimer = { flowName -> "Only the presented IDs are supported and accepted by $flowName. Make sure to provide one of them." },
    selectCountryPlaceholder = "Select country",
    presentPassport = "Present Your Passport",
    presentId = "Present Your ID",
    watchCapturePassport = "Watch How Easy It Is To Capture Your Passport",
    watchCaptureId = "Watch How Easy It Is To Capture Your ID",
    lightingTip = "Just make sure to be in a well lit area with no direct light reflecting on the ID or Passport presented.",

    faceMatch = "Face Match",
    watchCaptureFace = "Watch How Easy It Is\nTo Take A Selfie",
    faceCaptureTip = "The selfie includes liveness capture to ensure you're real, follow the on screen instructions.",
    verificationSuccess = "Verification Successful",
    verificationFail = "Verification UnSuccessful",
    verificationSuccessMsg = "We have been able to make sure its you!",
    verificationFailMsg = "Your face did not match with the provided document. Provide another document or confirm.",
    confirmProceed = "Confirm & Proceed",
    provideSupportingId = "Provide Supporting ID to match with",
    overrideProceed = "Override & Proceed",
    matchLabel = "Match",
    processingFace = "Processing Face please wait",
    uploadingFace = "Uploading Face please wait",
    faceErrorLiveTitle = "We couldn't verify a live face. Please try again.",
    faceErrorGeneralTitle = "Let's try again",
    faceErrorLiveMsg = "We could not verify a live face. Please ensure you are in a well-lit area, and avoid using photos or videos",
    faceErrorGeneralMsg = "Please make sure your face is well lit, look directly at the camera, and avoid using photos or videos",

    processingId = "Processing ID please wait",
    uploadingId = "Uploading ID please wait",
    idProcessedOk = "ID Processed Successfully",
    idErrorTitle = "Oops unable to Process ID Provided",
    idErrorMsg = "Make sure presented ID is clear and does not have any light reflections on it. Try presenting the ID vertically if your camera resolution is low to ease the extraction process.",
    captureBackId = "Capture Back of ID",
    flipCardMsg = "Please flip the card provided to take the back of the card",
    expectedCardType = "Expected Card Type",
    livenessErrorTitle = "Seems like you didn't provide a real ID",
    livenessErrorMsg = { flowName -> "Make sure its one of the above IDs presented and allowed by $flowName to verify your identity." },
    passportExpiredTitle = "Expired Passport Detected!",
    passportExpiredMsg = "Your passport appears to be expired. Please use a valid, non-expired passport to complete the verification process.",
    wrongTemplateTitle = "Unsupported ID Provided \n Wrong Template",
    wrongTemplateMsg = { flowName -> "Make sure its one of the above IDs presented and allowed by $flowName to verify your identity." },

    readyToSubmit = "Ready to Submit?",
    swipeToConfirm = "Swipe the button below to confirm your submission.",
    submissionError = "We couldn't complete your submission. Check your connection and retry.",
    swipeToSubmit = "Swipe to Submit",

    somethingWentWrong = "Something went wrong",

    captureQr = "Capture QR Code",
    watchCaptureQr = "Watch How Easy It Is\nTo Capture Your ID Qr Code",
    qrLightingTip = "Just make sure to be in a well lit area with no direct light reflecting on the ID .",

    nfcCapture = "NFC Based Capture",
    nfcInitialFeedback = "Position the passport on the bottom of the phone where the NFC chip reader is and ensure that you have the passport close enough for detection and reading.",
    nfcNotSupported = "NFC Not supported on this device.",
    nfcReading = "Nfc reading...",
    nfcConnectionLost = "Connection lost. Keep the phone still on the passport and try again.",
    nfcDetected = "NFC DETECTED",

    iAgreeTerms = "I agree to the terms and conditions",
    filesReviewedApproved = "Files Reviewed and Approved",
    emailVerificationTitle = "Email to Receive a Verification Code",
    phoneNumberLabel = "Phone Number",
    reviewApproveFiles = "Please review and approve the below files",
    thankYouForApproving = "Thank you for approving",
    agreementTitle = "Agreement",
    validateOtpFirst = "Validate OTP First",
    acceptTermsAndSign = "Accept Terms & Sign",
    acceptTermsOnly = "Accept Terms",
    approve = "Approve",

    holdSteady = "Hold Steady",
    holdYourHand = "Please Hold Your Hand",
    increaseLighting = "Please increase the lighting",
    reduceLighting = "Please reduce the lighting",
    centerCard = "Please center your card",
    movePassportCloser = "Move Passport Closer",
    movePassportFurther = "Move Passport Further",
    moveIdCloser = "Move ID Closer",
    moveIdFurther = "Move ID Further",
    moveFaceCloser = "Please Move Closer",
    moveFaceFurther = "Please Move Further",
    moveFaceLeft = "Please move your face left",
    moveFaceRight = "Please move your face right",
    moveFaceUp = "Please move your face up",
    moveFaceDown = "Please move your face down",
    winkLeftEye = "Please wink with your left eye",
    winkRightEye = "Please wink with your right eye",
    blinkEyes = "Please blink your eyes",
    tiltHeadRight = "Please tilt your head to the right",
    tiltHeadLeft = "Please tilt your head to the left",
    turnHeadRight = "Please turn your head to the right",
    turnHeadLeft = "Please turn your head to the left",
    lowerHead = "Please lower your head",
    raiseHead = "Please raise your head",
    faceWithinCircle = "Please face within circle",
    centerFace = "Please center your face",
    multipleFacesDetected = "We detected more than one face. Please keep just your face in view.",

    failedToLoadPdf = "Failed to load PDF",
    noPdfViewerFound = "No PDF viewer app found",
    failedToOpenPdf = "Failed to open PDF",

    otpLabel = { size -> "OTP ($size)" },
    sendOtp = "Send OTP",
    sendingOtp = "Sending OTP...",
    enterOtp = "Enter OTP",
    verifiedSuccessfully = "Verified successfully",
    otpVerifying = "Otp verifying ...",
    resendOtp = "Resend OTP",
    resendIn = { countdown -> "Resend in $countdown" },
    failedToSendOtp = "Failed to send OTP. Please try again.",
    invalidOtp = "Invalid OTP. Please try again.",
    invalidEmail = "Please enter a valid email address",
    invalidPhone = "Please enter a valid phone number",
    fieldRequired = "This field is required",
    minLengthError = { min -> "Minimum $min characters required" },
    maxLengthError = { max -> "Maximum $max characters allowed" },
    invalidValue = "Please enter a valid value",
    stepperProgress = { current, total -> "Step $current out of $total steps" },
    searchPlaceholder = "Search...",
    noResultsFound = "No results found",
    chooseCode = "Choose code",
    signatureTitle = "Signature",
    confirmSignature = "Confirm",
    confirmedSignature = "Confirmed",
    stepNameFormat = { n, name -> "Step $n: $name" },
    okButton = "OK",
    cancelButton = "CANCEL",

    fieldFirstName = "First Name",
    fieldLastName = "Last Name",
    fieldFatherName = "Father Name",
    fieldMotherName = "Mother Name",
    fieldBirthDate = "Birth Date",
    fieldExpiryDate = "Expiry Date",
    fieldCountry = "Country",
    fieldNationality = "Nationality",
    fieldDocNumber = "Document Number",
    fieldIdType = "ID Type",
    fieldPlaceOfBirth = "Place of Birth",
    fieldDocType = "Document Type",
    fieldCivilRegister = "Civil Register Number",
    fieldDateOfIssuance = "Date of Issuance",
    fieldGender = "Gender",
    fieldMaritalStatus = "Marital Status",
    fieldPlaceOfResidence = "Place of Residence",
    fieldProvince = "Province",
    fieldGovernorate = "Governorate",
)

private val arabicStrings = FlowStrings(
    next = "التالي",
    retry = "إعادة المحاولة",
    skip = "تخطي",
    letsStart = "لنبدأ",
    accept = "قبول",
    decline = "رفض",

    onboardingTitle = { count -> "أكمل تسجيلك\nفي $count ${if (count == 1) "خطوة" else "خطوات"}" },
    onboardingSubtitle = "ستشمل التحقق من هويتك ووجهك — سريعة وسهلة وآمنة.",
    thankYou = "شكراً لك!",
    completedSteps = { count -> "تمت $count ${if (count == 1) "خطوة" else "خطوات"} بنجاح" },

    stepTermsName = "الشروط والأحكام",
    stepTermsDesc = "اقرأ ووافق على الشروط والأحكام.",
    stepIdName = "مسح هويتك",
    stepIdDesc = "التقط صورة لبطاقتك الوطنية أو جواز سفرك للتحقق من هويتك.",
    stepFaceName = "صورة شخصية",
    stepFaceDesc = "استخدم الكاميرا للتحقق من هويتك بصورة شخصية سريعة.",
    stepDataEntryName = "تسجيل المعلومات",
    stepDataEntryDesc = "قدّم بياناتك الشخصية الأساسية كالاسم والعنوان وتفاصيل العمل.",
    stepSigningName = "التوقيع الإلكتروني",
    stepSigningDesc = "قدّم توقيعاً رقمياً لإتمام التسجيل.",

    restOfWorld = "بقية دول العالم",
    chooseCountry = "اختر بلد إقامتك",
    selectDocument = "اختر نوع الوثيقة",
    passport = "جواز السفر",
    supportedIds = "الهويات المدعومة",
    viewMore = "عرض المزيد",
    idDisclaimer = { flowName -> "الهويات المعروضة فقط هي المدعومة والمقبولة من قِبل $flowName. تأكد من تقديم إحداها." },
    selectCountryPlaceholder = "اختر الدولة",
    presentPassport = "قدّم جواز سفرك",
    presentId = "قدّم هويتك",
    watchCapturePassport = "شاهد كم هو سهل التقاط صورة جواز سفرك",
    watchCaptureId = "شاهد كم هو سهل التقاط صورة هويتك",
    lightingTip = "تأكد من وجودك في منطقة جيدة الإضاءة بعيداً عن أي انعكاسات ضوئية مباشرة.",

    faceMatch = "مطابقة الوجه",
    watchCaptureFace = "شاهد كم هو سهل\nالتقاط صورة شخصية",
    faceCaptureTip = "تتضمن الصورة اكتشاف الحيوية للتأكد من أنك حقيقي، اتبع التعليمات على الشاشة.",
    verificationSuccess = "تم التحقق بنجاح",
    verificationFail = "فشل التحقق",
    verificationSuccessMsg = "تمكنّا من التأكد من أنك أنت!",
    verificationFailMsg = "وجهك لا يتطابق مع الوثيقة المقدّمة. قدّم وثيقة أخرى أو تأكد.",
    confirmProceed = "تأكيد والمتابعة",
    provideSupportingId = "قدّم هوية داعمة للمطابقة",
    overrideProceed = "تجاوز والمتابعة",
    matchLabel = "تطابق",
    processingFace = "جارٍ معالجة الوجه، يرجى الانتظار",
    uploadingFace = "جارٍ تحميل الوجه، يرجى الانتظار",
    faceErrorLiveTitle = "تعذّر التحقق من وجه حقيقي. يرجى المحاولة مجدداً.",
    faceErrorGeneralTitle = "لنحاول مرة أخرى",
    faceErrorLiveMsg = "تعذّر التحقق من وجه حقيقي. تأكد من وجودك في منطقة جيدة الإضاءة وتجنب استخدام الصور أو مقاطع الفيديو.",
    faceErrorGeneralMsg = "تأكد من إضاءة وجهك جيداً، وانظر مباشرة إلى الكاميرا، وتجنب استخدام الصور أو مقاطع الفيديو.",

    processingId = "جارٍ معالجة الهوية، يرجى الانتظار",
    uploadingId = "جارٍ تحميل الهوية، يرجى الانتظار",
    idProcessedOk = "تمت معالجة الهوية بنجاح",
    idErrorTitle = "عذراً، تعذّر معالجة الهوية المقدّمة",
    idErrorMsg = "تأكد من أن الهوية المقدّمة واضحة وخالية من أي انعكاسات ضوئية. حاول تقديمها بشكل عمودي إذا كانت دقة كاميرتك منخفضة.",
    captureBackId = "التقاط الجهة الخلفية للهوية",
    flipCardMsg = "يرجى قلب البطاقة لالتقاط الجهة الخلفية",
    expectedCardType = "نوع البطاقة المتوقع",
    livenessErrorTitle = "يبدو أنك لم تقدّم هوية حقيقية",
    livenessErrorMsg = { flowName -> "تأكد من أنها إحدى الهويات المعتمدة المسموح بها من قِبل $flowName للتحقق من هويتك." },
    passportExpiredTitle = "تم اكتشاف جواز سفر منتهي الصلاحية!",
    passportExpiredMsg = "يبدو أن جواز سفرك منتهي الصلاحية. يرجى استخدام جواز سفر ساري المفعول لإتمام عملية التحقق.",
    wrongTemplateTitle = "هوية غير مدعومة\nقالب خاطئ",
    wrongTemplateMsg = { flowName -> "تأكد من أنها إحدى الهويات المعتمدة المسموح بها من قِبل $flowName." },

    readyToSubmit = "هل أنت مستعد للإرسال؟",
    swipeToConfirm = "اسحب الزر أدناه لتأكيد الإرسال.",
    submissionError = "تعذّر إتمام إرسالك. تحقق من اتصالك وأعد المحاولة.",
    swipeToSubmit = "اسحب للإرسال",

    somethingWentWrong = "حدث خطأ ما",

    captureQr = "التقاط رمز QR",
    watchCaptureQr = "شاهد كم هو سهل\nالتقاط رمز QR لهويتك",
    qrLightingTip = "تأكد من وجودك في منطقة جيدة الإضاءة بعيداً عن أي انعكاسات ضوئية مباشرة.",

    nfcCapture = "التقاط NFC",
    nfcInitialFeedback = "ضع جواز السفر في الجزء السفلي من الهاتف حيث يوجد قارئ NFC، وتأكد من قرب جواز السفر بما يكفي للكشف والقراءة.",
    nfcNotSupported = ".NFC غير مدعوم على هذا الجهاز",
    nfcReading = "...جارٍ قراءة NFC",
    nfcConnectionLost = "انقطع الاتصال. أبقِ الهاتف ثابتاً على جواز السفر وأعد المحاولة.",
    nfcDetected = "تم اكتشاف NFC",

    iAgreeTerms = "أوافق على الشروط والأحكام",
    filesReviewedApproved = "تمت مراجعة الملفات والموافقة عليها",
    emailVerificationTitle = "البريد الإلكتروني لاستقبال رمز التحقق",
    phoneNumberLabel = "رقم الهاتف",
    reviewApproveFiles = "يرجى مراجعة الملفات أدناه والموافقة عليها",
    thankYouForApproving = "شكراً لك على الموافقة",
    agreementTitle = "اتفاقية",
    validateOtpFirst = "يرجى التحقق من الرمز أولاً",
    acceptTermsAndSign = "الموافقة على الشروط والتوقيع",
    acceptTermsOnly = "الموافقة على الشروط",
    approve = "موافقة",

    holdSteady = "أبقِ ثابتاً",
    holdYourHand = "يرجى تثبيت يدك",
    increaseLighting = "يرجى زيادة الإضاءة",
    reduceLighting = "يرجى تقليل الإضاءة",
    centerCard = "يرجى توسيط البطاقة",
    movePassportCloser = "اقترب بجواز السفر أكثر",
    movePassportFurther = "ابعد جواز السفر قليلاً",
    moveIdCloser = "اقترب بالهوية أكثر",
    moveIdFurther = "ابعد الهوية قليلاً",
    moveFaceCloser = "يرجى الاقتراب أكثر",
    moveFaceFurther = "يرجى الابتعاد قليلاً",
    moveFaceLeft = "يرجى تحريك وجهك إلى اليسار",
    moveFaceRight = "يرجى تحريك وجهك إلى اليمين",
    moveFaceUp = "يرجى تحريك وجهك إلى الأعلى",
    moveFaceDown = "يرجى تحريك وجهك إلى الأسفل",
    winkLeftEye = "يرجى الغمز بعينك اليسرى",
    winkRightEye = "يرجى الغمز بعينك اليمنى",
    blinkEyes = "يرجى ومض عينيك",
    tiltHeadRight = "يرجى إمالة رأسك إلى اليمين",
    tiltHeadLeft = "يرجى إمالة رأسك إلى اليسار",
    turnHeadRight = "يرجى إدارة رأسك إلى اليمين",
    turnHeadLeft = "يرجى إدارة رأسك إلى اليسار",
    lowerHead = "يرجى خفض رأسك",
    raiseHead = "يرجى رفع رأسك",
    faceWithinCircle = "يرجى وضع وجهك داخل الدائرة",
    centerFace = "يرجى توسيط وجهك",
    multipleFacesDetected = "تم اكتشاف أكثر من وجه. يرجى الإبقاء على وجهك فقط في إطار الكاميرا.",

    failedToLoadPdf = "فشل تحميل ملف PDF",
    noPdfViewerFound = "لم يتم العثور على تطبيق لعرض PDF",
    failedToOpenPdf = "فشل فتح ملف PDF",

    otpLabel = { size -> "رمز OTP ($size)" },
    sendOtp = "إرسال رمز التحقق",
    sendingOtp = "...جارٍ إرسال الرمز",
    enterOtp = "أدخل رمز التحقق",
    verifiedSuccessfully = "تم التحقق بنجاح",
    otpVerifying = "...جارٍ التحقق من الرمز",
    resendOtp = "إعادة إرسال الرمز",
    resendIn = { countdown -> "إعادة الإرسال بعد $countdown" },
    failedToSendOtp = "فشل إرسال الرمز. يرجى المحاولة مجدداً.",
    invalidOtp = "الرمز غير صحيح. يرجى المحاولة مجدداً.",
    invalidEmail = "يرجى إدخال بريد إلكتروني صحيح",
    invalidPhone = "يرجى إدخال رقم هاتف صحيح",
    fieldRequired = "هذا الحقل مطلوب",
    minLengthError = { min -> "الحد الأدنى $min حرف مطلوب" },
    maxLengthError = { max -> "الحد الأقصى $max حرف مسموح به" },
    invalidValue = "يرجى إدخال قيمة صحيحة",
    stepperProgress = { current, total -> "الخطوة $current من $total" },
    searchPlaceholder = "بحث...",
    noResultsFound = "لا توجد نتائج",
    chooseCode = "اختر رمز الدولة",
    signatureTitle = "التوقيع",
    confirmSignature = "تأكيد",
    confirmedSignature = "تم التأكيد",
    stepNameFormat = { n, name -> "الخطوة $n: $name" },
    okButton = "موافق",
    cancelButton = "إلغاء",

    fieldFirstName = "الاسم الأول",
    fieldLastName = "اسم العائلة",
    fieldFatherName = "اسم الأب",
    fieldMotherName = "اسم الأم",
    fieldBirthDate = "تاريخ الميلاد",
    fieldExpiryDate = "تاريخ انتهاء الصلاحية",
    fieldCountry = "الدولة",
    fieldNationality = "الجنسية",
    fieldDocNumber = "رقم الوثيقة",
    fieldIdType = "نوع الهوية",
    fieldPlaceOfBirth = "مكان الميلاد",
    fieldDocType = "نوع الوثيقة",
    fieldCivilRegister = "رقم السجل المدني",
    fieldDateOfIssuance = "تاريخ الإصدار",
    fieldGender = "الجنس",
    fieldMaritalStatus = "الحالة الاجتماعية",
    fieldPlaceOfResidence = "مكان الإقامة",
    fieldProvince = "المحافظة",
    fieldGovernorate = "المحافظة/الولاية",
)

fun flowStrings(): FlowStrings =
    if (BaseTheme.BaseUiLanguage == UiLanguage.Arabic) arabicStrings else englishStrings